######### 빈 데이터베이스 에서 작업 #########
# 내 DB의 모든 테이블 조회 명령어
SHOW TABLES

# 테이블 생성
CREATE TABLE KOPO_PRODUCT_VOLUME(
	REGIONID VARCHAR(20),
	PRODUCTGROUP VARCHAR(20),
	YEARWEEK VARCHAR(6),
	VOLUME DOUBLE
)

# 테이블 조회
SELECT *
FROM KOPO_PRODUCT_VOLUME

# 테이블 조회 (!컬럼의 이름은 쓰고 들여쓰기 조심!!!)
SELECT REGIONID,
	PRODUCTGROUP,
	YEARWEEK,
	VOLUME 
FROM KOPO_PRODUCT_VOLUME

# 데이터 삽입 (전체 컬럼)
INSERT INTO KOPO_PRODUCT_VOLUME
VALUES('서울','한국은행','202404',2000)

# 데이터 삽입 (특정 컬럼)
INSERT INTO KOPO_PRODUCT_VOLUME
(REGIONID,PRODUCTGROUP,YEARWEEK)
VALUES('서울','한국은행','202403')

# 데이터 삭제
DELETE FROM KOPO_PRODUCT_VOLUME
WHERE YEARWEEK = '202402'

SELECT *
FROM KOPO_PRODUCT_VOLUME

UPDATE KOPO_PRODUCT_VOLUME
SET VOLUME = 9999

SELECT *
FROM KOPO_PRODUCT_VOLUME

WHERE YEARWEEK = '202401'

